--how to complile java project (pure Java without Framework)
--first complile 
--javac com/smarthome/*.java
--then run
--java -cp . com.smarthome.Main

--vim.lsp.enable("jdtls")
--require 'lspconfig'.jdtls.setup({
	--settings = {
		--java = {
			--project = {
				--referencedLibraries = {},
				--sourcePaths = { "src" } -- This ensures `src` is treated as source root
			--}
		--}
	--},
	--on_attach = function(client, bufnr)
		--print('hello Java')
	--end,
--})

